#!/usr/bin/env python3
"""
A wizard — walks a human through a manual procedure step by step.
Generated by the /wizard skill.

Everything above the "STAGES" marker is the wizard library: do not hand-edit it.
Author the per-step stages below the marker.

Usage:
  python template.py
"""
import getpass
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import webbrowser
from pathlib import Path


# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

is_tty = sys.stdout.isatty()
is_windows = sys.platform == "win32"

# Best-effort terminal colors
BOLD = DIM = RESET = BLUE = GREEN = YELLOW = RED = ""
if is_tty:
    try:
        import colorama
        colorama.init()
        BOLD, DIM, RESET, BLUE, GREEN, YELLOW, RED = (
            colorama.Style.BRIGHT, colorama.Style.DIM, colorama.Style.RESET_ALL,
            colorama.Fore.BLUE, colorama.Fore.GREEN, colorama.Fore.YELLOW, colorama.Fore.RED,
        )
    except ImportError:
        if not is_windows:
            BOLD = "\033[1m"
            DIM = "\033[2m"
            RESET = "\033[0m"
            BLUE = "\033[34m"
            GREEN = "\033[32m"
            YELLOW = "\033[33m"
            RED = "\033[31m"

# Author sets this at the top of the stages section.
TOTAL_STAGES = 0

_stage_index = 0
_env_file = os.environ.get("ENV_FILE", ".env")
_written_env = []
_written_secret = []
_skipped = []


def _clear():
    """Wipe the terminal so only the current step is on screen."""
    if not is_tty:
        return
    os.system("cls" if is_windows else "clear")


def banner(title):
    """Opening frame: what this wizard does."""
    _clear()
    print(f"\n{BOLD}{BLUE}  {title}{RESET}")
    print(f"{DIM}  {TOTAL_STAGES} stages{RESET}\n")
    print(f"{DIM}  You drive the browser; this wizard tells you exactly what to do and")
    print(f"  captures the values you copy back. Stop any time with Ctrl-C and re-run")
    print(f"  later — it remembers values already saved.{RESET}\n")
    pause("Ready to start?")


def stage(name):
    """Clear the screen, then announce a stage and show progress."""
    global _stage_index
    _clear()
    _stage_index += 1
    print(f"\n{BOLD}{BLUE}▸ Stage {_stage_index}/{TOTAL_STAGES} · {name}{RESET}\n")


def say(text):
    print(f"  {text}")


def step(text):
    print(f"  {BLUE}•{RESET} {text}")


def note(text):
    print(f"  {DIM}{text}{RESET}")


def warn(text):
    print(f"  {YELLOW}⚠ {text}{RESET}")


def open_url(url):
    """Open the human's browser, cross-platform."""
    print(f"  {GREEN}↗ opening{RESET} {url}")
    try:
        webbrowser.open(url)
    except Exception:
        warn(f"couldn't open a browser — visit it manually: {url}")


def pause(prompt="Press Enter to continue"):
    input(f"  {DIM}{prompt}{RESET} ")


def confirm(question):
    """y/N gate; returns True on yes."""
    reply = input(f"  {YELLOW}? {question} [y/N] {RESET}").strip()
    return reply.lower().startswith("y")


def _existing(key):
    """Return current value of KEY in the env file, if any."""
    if not os.path.exists(_env_file):
        return None
    try:
        with open(_env_file, "r", encoding="utf-8") as f:
            for line in f:
                m = re.match(rf"^{re.escape(key)}=(.*)", line)
                if m:
                    return m.group(1).strip()
    except Exception:
        pass
    return None


def ask(key, prompt):
    """Read a value into a variable named KEY. Offers existing .env value as default."""
    current = _existing(key)
    if current:
        value = input(f"  {BOLD}{prompt}{RESET} {DIM}[Enter keeps current]{RESET} ")
    else:
        value = input(f"  {BOLD}{prompt}{RESET} ")
    if not value and current:
        value = current
    globals()[key] = value
    return value


def ask_secret(key, prompt):
    """Like ask, but input is hidden."""
    current = _existing(key)
    if current:
        value = getpass.getpass(f"  {BOLD}{prompt}{RESET} {DIM}[Enter keeps current]{RESET} ")
    else:
        value = getpass.getpass(f"  {BOLD}{prompt}{RESET} ")
    if not value and current:
        value = current
    globals()[key] = value
    return value


def write_env(key, value):
    """Upsert KEY=VALUE into the env file (creates it; replaces any existing line)."""
    lines = []
    if os.path.exists(_env_file):
        with open(_env_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
    # Remove existing line
    pattern = re.compile(rf"^{re.escape(key)}=.*$")
    lines = [line for line in lines if not pattern.match(line.rstrip("\n"))]
    lines.append(f"{key}={value}\n")
    with open(_env_file, "w", encoding="utf-8") as f:
        f.writelines(lines)
    _written_env.append(key)
    print(f"  {GREEN}✓ wrote{RESET} {key} → {_env_file}")


def _gh_available():
    return shutil.which("gh") is not None


def set_secret(name, value):
    """Set a GitHub Actions repo secret via gh. Falls back to a warning."""
    if _gh_available():
        try:
            proc = subprocess.run(
                ["gh", "secret", "set", name],
                input=value,
                text=True,
                capture_output=True,
            )
            if proc.returncode == 0:
                _written_secret.append(name)
                print(f"  {GREEN}✓ set{RESET} GitHub secret {name}")
                return
        except Exception:
            pass
    _skipped.append(f"GitHub secret {name} (set it manually: gh secret set {name})")
    warn(f"skipped GitHub secret {name} — gh not ready; set it later")


def set_var(name, value):
    """Set a GitHub Actions repo variable (non-secret)."""
    if _gh_available():
        try:
            proc = subprocess.run(
                ["gh", "variable", "set", name, "--body", value],
                capture_output=True,
                text=True,
            )
            if proc.returncode == 0:
                print(f"  {GREEN}✓ set{RESET} GitHub variable {name}")
                return
        except Exception:
            pass
    _skipped.append(f"GitHub variable {name}")
    warn(f"skipped GitHub variable {name} — gh not ready; set it later")


def finish():
    """Clear, then a closing summary of everything configured."""
    _clear()
    print(f"\n{BOLD}{GREEN}  ✓ Setup complete{RESET}\n")
    if _written_env:
        note(f"wrote {len(_written_env)} value(s) to {_env_file}: {', '.join(_written_env)}")
    if _written_secret:
        note(f"set {len(_written_secret)} GitHub secret(s): {', '.join(_written_secret)}")
    if _skipped:
        print()
        warn("still to do by hand:")
        for s in _skipped:
            note(f"  - {s}")
    print()


# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES = 1

banner("Stripe setup")

# ── Example stage: replace with your real steps ───────────────────────────
stage("Stripe — API keys")
say("We'll grab your Stripe test keys and store them for local dev + CI.")
open_url("https://dashboard.stripe.com/test/apikeys")
step("On the API keys page, copy the Publishable key (starts pk_test_).")
ask("STRIPE_PUBLISHABLE_KEY", "Paste the publishable key:")
step("Click 'Reveal test key' on the Secret key row, then copy it.")
ask_secret("STRIPE_SECRET_KEY", "Paste the secret key:")
write_env("STRIPE_PUBLISHABLE_KEY", STRIPE_PUBLISHABLE_KEY)
write_env("STRIPE_SECRET_KEY", STRIPE_SECRET_KEY)
set_secret("STRIPE_SECRET_KEY", STRIPE_SECRET_KEY)  # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish()
