#!/usr/bin/env python3
"""Blocks AI signatures in git commits, file writes, and uncommitted changes.

Handles two events, dispatched on `hook_event_name`:
  PreToolUse - exec (git commit message, including -F/--file), write, edit
  Stop       - scans staged changes for AI signatures before the agent stops

Stdin payloads (per /cli/extensibility/hooks/lifecycle-hooks):
  PreToolUse {"hook_event_name": "PreToolUse", "tool_name": "exec",
              "tool_input": {"command": "..."}}
  Stop       {"hook_event_name": "Stop", "stop_hook_active": false}

Exit codes (per /cli/extensibility/hooks/overview#exit-codes):
  0 = allow, 2 = block.

Enforces AGENTS.md Rule 2 (no AI signatures in deliverables).
"""
import sys, json, re, os, subprocess

SIGNATURES = (
    r"Generated with \[?Devin\]?",
    r"Co-Authored-By:\s*Devin",
    r"Co-Authored-By:.*\bAI\b",
    r"Co-Authored-By:.*\bClaude\b",
    r"Co-Authored-By:.*\bCopilot\b",
    r"Co-Authored-By:.*\bGPT\b",
    r"Co-Authored-By:.*\bGemini\b",
    r"Generated by Claude",
    r"Generated with Claude",
    r"Generated by ChatGPT",
    r"Generated by GitHub Copilot",
    r"Generated by Gemini",
    r"Generated with Gemini",
    r"Generated by Cursor",
    r"Generated by Windsurf",
    r"\U0001F916 Generated by",
    r"\bAI-generated\b",
    r"\bAI-assisted\b",
    r"written by (?:an? )AI\b",
)
PATTERN = re.compile("|".join(SIGNATURES), re.IGNORECASE)


def block(reason):
    """Emit a block decision and exit with code 2 (deny)."""
    print(json.dumps({"decision": "block", "reason": reason}))
    sys.exit(2)


def check_text(text):
    return bool(text) and bool(PATTERN.search(text))


def read_commit_file(filepath):
    """Read a commit message from a -F/--file path; empty string on error."""
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            return f.read()
    except (OSError, IOError):
        return ""


def extract_commit_file(command):
    """Extract the filepath from 'git commit -F <file>' / '--file=<file>'."""
    for pattern in (
        r"--file=([^\s]+)",
        r"--file\s+([^\s]+)",
        r"(?:^|\s)-F\s+([^\s]+)",
        r"(?:^|\s)-F([^\s]+)",
    ):
        m = re.search(pattern, command)
        if m:
            return m.group(1).strip().strip("\"'")
    return None


def handle_stop(_data):
    """Scan staged and unstaged changes for AI signatures."""
    cwd = os.environ.get("DEVIN_PROJECT_DIR") or os.getcwd()
    for args in (
        ["git", "diff", "--cached", "--unified=0"],
        ["git", "diff", "--unified=0"],
    ):
        try:
            result = subprocess.run(
                args, capture_output=True, text=True, timeout=10, cwd=cwd
            )
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            return  # no git or no repo: allow
        if result.returncode == 0 and check_text(result.stdout):
            scope = "staged" if "--cached" in args else "unstaged"
            block(
                f"AI signature detected in {scope} changes. Remove it before "
                "stopping (AGENTS.md Rule 2)."
            )


def handle_pre_tool_use(data):
    tool_name = data.get("tool_name", "") or ""
    tool_input = data.get("tool_input") or {}
    if not isinstance(tool_input, dict):
        return

    if tool_name == "exec":
        command = tool_input.get("command", "") or ""
        if "git commit" not in command.lower():
            return
        if check_text(command):
            block(
                "AI signature detected in the git commit message (AGENTS.md Rule 2)."
            )
        commit_file = extract_commit_file(command)
        if commit_file:
            content = read_commit_file(commit_file)
            if check_text(content):
                block(
                    f"AI signature detected in the commit message file "
                    f"'{commit_file}' (AGENTS.md Rule 2)."
                )
        return

    if tool_name in ("write", "edit"):
        content = tool_input.get("content") or tool_input.get("new_string") or ""
        if check_text(content):
            block(
                f"AI signature detected in {tool_name} content (AGENTS.md Rule 2)."
            )


HANDLERS = {
    "PreToolUse": handle_pre_tool_use,
    "Stop": handle_stop,
}


def main():
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError, ValueError):
        sys.exit(0)  # fail-open

    handler = HANDLERS.get(data.get("hook_event_name", ""))
    if handler is not None:
        handler(data)

    sys.exit(0)


if __name__ == "__main__":
    main()
