#!/usr/bin/env python3
"""PreToolUse/Stop hook: blocks AI signatures in git commits, file writes, and uncommitted changes.

Reads tool input JSON from stdin. Exit 0 = allow, exit 1 = block.
Checks:
- exec: if git commit, parse commit message for AI signatures (including -F file)
- write/edit: if file content contains AI signatures
- Stop event: scans uncommitted git changes for AI signatures
"""
import sys, json, re, os, subprocess

SIGNATURES = [
    r"Generated with \[?Devin\]?",
    r"Co-Authored-By: Devin",
    r"Co-Authored-By:.*AI",
    r"Generated by Claude",
    r"Generated with Claude",
    r"Generated by ChatGPT",
    r"Generated by GitHub Copilot",
    r"🤖 Generated by",
    r"AI-generated",
]
PATTERN = re.compile("|".join(SIGNATURES), re.IGNORECASE)

def check_text(text):
    return bool(PATTERN.search(text))

def read_commit_file(filepath):
    """Read commit message from -F file, return empty string on error."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            return f.read()
    except (OSError, IOError):
        return ""

def extract_commit_file(command):
    """Extract filepath from 'git commit -F <file>' or 'git commit --file=<file>'."""
    # Match --file=<file> first (most specific)
    m = re.search(r'--file=([^\s]+)', command)
    if m:
        return m.group(1).strip().strip('"').strip("'")
    # Match --file <file>
    m = re.search(r'--file\s+([^\s]+)', command)
    if m:
        return m.group(1).strip().strip('"').strip("'")
    # Match -F <file> (with space) — ensure -F is a standalone flag, not part of another word
    m = re.search(r'(?:^|\s)-F\s+([^\s]+)', command)
    if m:
        return m.group(1).strip().strip('"').strip("'")
    # Match -F<file> (no space) — ensure -F is at word boundary
    m = re.search(r'(?:^|\s)-F([^\s]+)', command)
    if m:
        return m.group(1).strip().strip('"').strip("'")
    return None

def main():
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)  # can't parse, allow

    tool = data.get("tool", "")
    tool_input = data.get("tool_input", {})
    event = data.get("event", "")

    # Stop event: scan uncommitted changes for AI signatures
    if event == "Stop" or tool == "Stop":
        try:
            result = subprocess.run(
                ["git", "diff", "--cached", "--unified=0"],
                capture_output=True, text=True, timeout=10, cwd=os.getcwd()
            )
            if result.returncode == 0 and check_text(result.stdout):
                print("BLOCKED: AI signature detected in staged changes. Remove before stopping.", file=sys.stderr)
                sys.exit(1)
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            pass  # no git or no repo, allow
        sys.exit(0)

    # Check exec for git commit with AI signature
    if tool == "exec":
        command = tool_input.get("command", "")
        if "git commit" in command.lower():
            # Check commit message in command (-m flag)
            if check_text(command):
                print("BLOCKED: AI signature detected in git commit message.", file=sys.stderr)
                sys.exit(1)
            # Check commit message from -F file
            commit_file = extract_commit_file(command)
            if commit_file:
                file_content = read_commit_file(commit_file)
                if file_content and check_text(file_content):
                    print(f"BLOCKED: AI signature detected in commit message file {commit_file}.", file=sys.stderr)
                    sys.exit(1)

    # Check write for AI signature in content
    if tool in ("write", "edit"):
        content = tool_input.get("content", "") or tool_input.get("new_string", "")
        if content and check_text(content):
            print("BLOCKED: AI signature detected in file content.", file=sys.stderr)
            sys.exit(1)

    sys.exit(0)

if __name__ == "__main__":
    main()
