#!/usr/bin/env python3
"""Validates skill format against Devin CLI quality standards.

Scans all SKILL.md files in skill directories and checks them against
the 8-point quality checklist from AGENTS.md Rule 3.

Usage:
  python validate-skill-format.py [path/to/skills/dir]
  python validate-skill-format.py --project   # scan .devin/skills/
  python validate-skill-format.py --global    # scan ~/.config/devin/skills/

If no args, scans bundle root skills/, project .devin/skills/, and global skill directories.

Checks (from AGENTS.md Rule 3, Skill Quality Standards):
  1. Frontmatter: name (lowercase, hyphens, max 64, matches dir) + description (max 1024)
  2. Discovery-friendly: description starts with "Use when"
  3. Devin-native tools: uses Devin CLI tool names
  4. Devin-native paths: uses .devin/ or ~/.config/devin/
  5. No AI signatures in skills
  6. No platform leakage

Source: AGENTS.md Rule 3, Skill Quality Standards.
  Automated validation prevents skills from drifting from quality standards.
"""
import sys, os, re


def devin_home():
    """Return the Devin user config home.

    Windows: %APPDATA%\\devin
    Unix: $XDG_CONFIG_HOME/devin or ~/.config/devin
    """
    appdata = os.environ.get("APPDATA", "")
    if appdata:
        return os.path.join(appdata, "devin")
    xdg = os.environ.get("XDG_CONFIG_HOME", "")
    if xdg:
        return os.path.join(xdg, "devin")
    return os.path.join(os.path.expanduser("~"), ".config", "devin")


# Frontmatter pattern
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)

# Non-Devin tool invocation patterns. `Task(` is case-sensitive on purpose: the
# lowercase word "task (" appears in ordinary prose and caused false positives.
NON_DEVIN_TOOLS = re.compile(r"(\bTask\s*\(|\bsubagent_type\s*[=:]|\bcreate_task\b|\bexecute_task\b)")

# Non-Devin paths
NON_DEVIN_PATHS = re.compile(r"(\.claude/|\.cursor/|\.github/copilot|~/.anthropic/|\.windsurf/|\.codeium/|\.continue/|\.aider/)", re.IGNORECASE)

# AI signatures
AI_SIGNATURES = re.compile(r"(Generated with \[?Devin\]?|Co-Authored-By:.*AI|Co-Authored-By:.*Claude|Co-Authored-By:.*Copilot|Co-Authored-By:.*GPT|Co-Authored-By:.*Gemini|Generated by Claude|Generated by ChatGPT|Generated by GitHub Copilot|Generated by Gemini|Generated by Cursor|Generated by Windsurf|\bAI-generated\b|\bAI-assisted\b)", re.IGNORECASE)

# Descriptive contexts where "AI-assisted" / "AI-generated" appears as a topic
# reference, not a signature claim. Must stay in sync with check-ai-signature.py.
AI_ALLOWED_CONTEXTS = (
    re.compile(r"\bAI-assisted\s+(?:tooling|tool|tools|development|review|testing|coding|workflow|workflows|approach|process|pipeline)\b", re.IGNORECASE),
    re.compile(r"\bAI-generated\s+(?:content|images|art|text|code|data|samples|examples|responses|output|outputs)\b", re.IGNORECASE),
)

# Valid name pattern
VALID_NAME = re.compile(r"^[a-z][a-z0-9-]{0,63}$")


KEY_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$")


def parse_frontmatter(content):
    """Extract a frontmatter dict from SKILL.md, joining folded multi-line values.

    YAML values may continue on following indented lines. Treating each line as
    its own key truncated long descriptions and produced false 'Use when'
    failures, so continuation lines are appended to the previous key.
    """
    match = FRONTMATTER_RE.match(content)
    if not match:
        return None, content
    rest = content[match.end():]
    fm = {}
    last_key = None
    for line in match.group(1).split("\n"):
        if not line.strip():
            continue
        m = KEY_RE.match(line)
        if m and not line[0].isspace():
            last_key = m.group(1).strip()
            fm[last_key] = m.group(2).strip()
        elif last_key is not None:
            # Continuation of the previous value (folded block or indented text).
            fm[last_key] = (fm[last_key] + " " + line.strip()).strip()
    return fm, rest


def validate_skill(skill_path):
    """Validate a single SKILL.md. Returns (score, issues)."""
    issues = []
    score = 100

    try:
        with open(skill_path, "r", encoding="utf-8") as f:
            content = f.read()
    except (OSError, IOError) as e:
        return 0, [f"cannot read file: {e}"]

    dir_name = os.path.basename(os.path.dirname(skill_path))

    # Check 1: Frontmatter exists
    fm, body = parse_frontmatter(content)
    if fm is None:
        issues.append("no frontmatter (--- ... --- block)")
        return 0, issues

    # Check 2: name field
    name = fm.get("name", "")
    if not name:
        issues.append("missing 'name' in frontmatter")
        score -= 20
    else:
        if not VALID_NAME.match(name):
            issues.append(f"name '{name}' must be lowercase, hyphens, max 64 chars, start with letter")
            score -= 10
        if name != dir_name:
            issues.append(f"name '{name}' does not match directory '{dir_name}'")
            score -= 10
        if len(name) > 64:
            issues.append(f"name exceeds 64 chars ({len(name)})")
            score -= 5

    # Check 3: description field
    desc = fm.get("description", "")
    if not desc:
        issues.append("missing 'description' in frontmatter")
        score -= 20
    else:
        if len(desc) > 1024:
            issues.append(f"description exceeds 1024 chars ({len(desc)})")
            score -= 10
        if not desc.strip().lower().startswith("use when"):
            issues.append("description should start with 'Use when'")
            score -= 5

    # Check 3b: model field must not use paid aliases (Rule 20)
    model = fm.get("model", "")
    if model:
        # "swe" alias is PAID ($2.5/$12.5 MTok) — must use "swe-1-7" (free)
        paid_aliases = {"swe", "opus", "sonnet", "haiku", "gpt-4", "gpt-4o", "gpt-5"}
        if model in paid_aliases:
            issues.append(f"model '{model}' is a paid alias — use 'swe-1-7' (free) or 'glm-5-2' (free) per Rule 20")
            score -= 10

    # Check 3c: subagent field must be boolean, not a profile string (docs.devin.ai creating-skills)
    # Profile selection uses `agent: <profile>`. A string `subagent: implementer`
    # silently breaks skill loading (skill absent from available_skills).
    subagent = fm.get("subagent", "")
    if subagent:
        if subagent not in ("true", "false"):
            issues.append(
                f"subagent '{subagent}' must be boolean (true/false), not a profile name. "
                f"Use `agent: <profile>` for profile selection. "
                f"A string value silently breaks skill loading."
            )
            score -= 45

    # Check 4: No non-Devin tool names
    if NON_DEVIN_TOOLS.search(content):
        matches = NON_DEVIN_TOOLS.findall(content)
        issues.append(f"non-Devin tool references found: {matches[:3]}")
        score -= 10

    # Check 5: No non-Devin paths
    if NON_DEVIN_PATHS.search(content):
        matches = NON_DEVIN_PATHS.findall(content)
        issues.append(f"non-Devin paths found: {matches[:3]}")
        score -= 10

    # Check 6: No AI signatures (strip allowed descriptive contexts first)
    stripped = content
    for ctx in AI_ALLOWED_CONTEXTS:
        stripped = ctx.sub("", stripped)
    if AI_SIGNATURES.search(stripped):
        issues.append("AI signature detected in skill content")
        score -= 15

    # Check 7: Has content (not just frontmatter)
    if len(body.strip()) < 50:
        issues.append("skill body is too short (<50 chars after frontmatter)")
        score -= 10

    return max(score, 0), issues


def scan_directory(skills_dir):
    """Scan all skills in a directory. Returns list of (path, score, issues)."""
    results = []
    if not os.path.isdir(skills_dir):
        return results

    for entry in os.listdir(skills_dir):
        skill_path = os.path.join(skills_dir, entry, "SKILL.md")
        if os.path.isfile(skill_path):
            score, issues = validate_skill(skill_path)
            results.append((skill_path, score, issues))

    return results


def main():
    dirs_to_scan = []

    if len(sys.argv) > 1:
        if sys.argv[1] == "--project":
            dirs_to_scan.append(os.path.join(os.getcwd(), ".devin", "skills"))
        elif sys.argv[1] == "--global":
            dirs_to_scan.append(os.path.join(devin_home(), "skills"))
        else:
            dirs_to_scan.append(sys.argv[1])
    else:
        # Scan bundle root, project .devin/skills/, and global installs
        # Bundle root 'skills/' is the source of truth for the devin-bundle repo.
        bundle_skills = os.path.join(os.getcwd(), "skills")
        if os.path.isdir(bundle_skills):
            dirs_to_scan.append(bundle_skills)
        dirs_to_scan.append(os.path.join(os.getcwd(), ".devin", "skills"))
        dirs_to_scan.append(os.path.join(devin_home(), "skills"))

    total = 0
    passing = 0
    failing = 0

    for skills_dir in dirs_to_scan:
        results = scan_directory(skills_dir)
        if not results:
            continue

        print(f"\nScanning: {skills_dir}", file=sys.stderr)
        for path, score, issues in sorted(results, key=lambda x: x[1]):
            total += 1
            rel_path = os.path.relpath(path, skills_dir)
            if score >= 80 and not issues:
                passing += 1
                print(f"  [PASS] {rel_path} (score: {score})", file=sys.stderr)
            elif score >= 60:
                passing += 1
                print(f"  [WARN] {rel_path} (score: {score})", file=sys.stderr)
                for issue in issues:
                    print(f"         - {issue}", file=sys.stderr)
            else:
                failing += 1
                print(f"  [FAIL] {rel_path} (score: {score})", file=sys.stderr)
                for issue in issues:
                    print(f"         - {issue}", file=sys.stderr)

    print(f"\nSkill Validation Summary:", file=sys.stderr)
    print(f"  Total: {total}  Passing: {passing}  Failing: {failing}", file=sys.stderr)

    if failing > 0:
        print(f"\n  {failing} skill(s) need fixes. See AGENTS.md Rule 3 for standards.", file=sys.stderr)

    sys.exit(1 if failing > 0 else 0)

if __name__ == "__main__":
    main()
